apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-buks-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-buks-frontend
  template:
    metadata:
      labels:
        app: gcp-buks-frontend
    spec:
      containers:
      - name: gcp-buks-frontend
        image: japhetism/gcp-buks-frontend:tagversion
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80



---


apiVersion: v1
kind: Service
metadata:
  name: gcp-buks-frontend
spec:
  type: NodePort
  selector:
    app: gcp-buks-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 32000