apiVersion: apps/v1
kind: Deployment
metadata:
  name: buks-frontend
  labels:
    app: buks-frontend
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: buks-frontend
      
  template:
    metadata:
      labels:
        app: buks-frontend
        tier: buks-frontend
    spec:
      containers:
        - name: buks-frontend
          image: japhetism/gcp-buks-frontend:tagversion
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: buks-frontend


---
apiVersion: v1
kind: Service
metadata:
  name: buks-frontend
  labels:
    app: buks-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: buks-frontend
    tier: buks-frontend
  type: LoadBalancer
